spring:
  application:
    name: chillguy
  profiles:
    active: dev  # 기본값(dev), 배포 시 'prod'로 변경
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: 900000 # 15분 (ms)
  refresh-token-validity: 1209600000 # 14일 (ms)


server:
  port: 8080  # 기본 포트 (환경별로 다르게 설정 가능)

# Swagger 설정 (배포 환경에서는 비활성화 가능)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    enabled: true
