spring:
  datasource:
    url: jdbc:mysql://mysql_container:3306/chillguy_music?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USER_NAME}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate # 운영 환경에서는 validate 추천 (데이터 손실 방지)
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# 배포용 CORS 설정 (배포된 프론트엔드만 허용)
cors:
  allowed-origins: "https://chillguy-music.com"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"

# 배포용 로깅 설정 (INFO 수준으로 설정)
logging:
  level:
    root: info
    org.springframework: warn
    security: warn

frontend:
  url: "https://chillguy-music.com"
