spring:
  application:
    name: chillguy
  profiles:
    active: prod  # 기본값(dev), 배포 시 'prod'로 변경
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
              - openid
              - https://www.googleapis.com/auth/youtube.force-ssl
              - https://www.googleapis.com/auth/youtube

gemini:
  url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=
  api-key: ${GEMINI_SECRET_KEY}

youtube:
  url: https://youtube.googleapis.com/youtube/v3
  api-key: ${YOUTUBE_SECRET_KEY}


jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: 900000 # 15분 (ms)
  refresh-token-validity: 1209600000 # 14일 (ms)


server:
  port: 8080  # 기본 포트 (환경별로 다르게 설정 가능)

# Swagger 설정 (배포 환경에서는 비활성화 가능)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    enabled: true

logging:
  level:
    root: debug
    org.springframework.web: debug
    org.springframework.security: debug
